services:
  database:
    image: postgres:17.4
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/resources/db:/temp/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clientes_db
    ports:
        - 5432:5432
volumes:
  pgdata:
